### ISSUE TITLE
About the experiment using The People Snapshot Dataset

### ISSUE THREAD

**Issue by TianyuanYang** [hustvl/GNeuVox#1]
Thank you for the excellent work!

When experimenting with The People Snapshot Dataset, there were some bugs when loading the data, which should be related to the dataset format. I don't know whether I did not find the right way to do it, but after making some simple changes to the code, it can run successfully.

https://github.com/hustvl/GNeuVox/blob/689378258e23de79e422e47e97b94253acb2a5f0/core/data/dataset/train.py#L169-L172

```
img_paths = list_files(os.path.join(self.dataset_path, 'images'), exts=['.png'])
```

https://github.com/hustvl/GNeuVox/blob/689378258e23de79e422e47e97b94253acb2a5f0/core/data/dataset/train.py#L376-L377
```
subject = self.now_subject
time_int = int(frame_name)
```

https://github.com/hustvl/GNeuVox/blob/689378258e23de79e422e47e97b94253acb2a5f0/core/data/dataset/eval_cam.py#L365
```
time_int = int(frame_name)
```

**Comment by taoranyi** [comment]
Thank you for your attention, there is indeed an issue here. The file has been incorrectly named and I will change it later.

**Comment by taoranyi** [comment]
Now, I have re-uploaded the dataset and have fixed this issue.
