### ISSUE TITLE
Rendering Camera angle issue for People Snapshot

### ISSUE THREAD

**Issue by Dipankar1997161** [hustvl/GNeuVox#6]
Hello @taoranyi,

I have trained all my models from scratch. For people-snapshot, The rendering result is good but the camera angle is not accurate.
for z-axis
![000002](https://github.com/hustvl/GNeuVox/assets/85514219/7761fad0-062d-46ad-b7a0-569a73298717)

for y-axis
![000002](https://github.com/hustvl/GNeuVox/assets/85514219/5707b90c-af66-4a93-a773-3cc8345066e8)

I have processed the file from EasyMocap "demo for motion capture", 
I am not understanding what could be the error.

I checked your cameras.pkl, it is the same as mine. Have you faced any issues like this?

**Comment by taoranyi** [comment]
I'm sorry, I have encountered the same issue and it has not been resolved yet.
