### ISSUE TITLE
Processing data with Easymocap doesn't produce masks, but the processing script requires masks.

### ISSUE THREAD

**Issue by ctalegaonkar** [hustvl/GNeuVox#7]
Is there a way to generate masks directly from the easymocap processing code?

**Comment by taoranyi** [comment]
There are many human matting methods available, I found [one](https://github.com/cxgincsu/SemanticGuidedHumanMatting) that may be suitable.

**Comment by ctalegaonkar** [comment]
Thanks, this worked quite well.
